### ISSUE TITLE
Remove trailing whitespace from path

### ISSUE THREAD

**Issue by grappler** [tlovett1/safe-redirect-manager#240] opened 2021-04-30 09:32 UTC
**Is your enhancement related to a problem? Please describe.**
A redirect that had been setup and I could not figure out why it was not working. The reason was a trailing whitespace in the from path.

**Describe the solution you'd like**
Either when saving the redirect or when comparing the paths the trailing whitespace should be automatically removed.

**Comment by Sidsector9** [comment] 2022-06-08 10:50
I've tested this in the develop branch and I'm unable to reproduce it. This may have been fixed. I'm closing this for now, please feel free to reopen if the issue persists.

**Closed as completed by Sidsector9** 2022-06-08 10:50 UTC
Labels: type:enhancement, help wanted
